### ISSUE TITLE
Listening for events

### ISSUE THREAD

**Issue by brock** [kreynolds/ruby-mios#12]
@kreynolds 

Is it possible with this gem to listen to events that happen on the MIOS? I was thinking about removing all of my scenes in Vera and managing them all in my own app, but I'd have to be notified if I physically flip a switch somewhere, or poll the devices for status. Any thoughts on how you'd go about this?

**Comment by kreynolds** [comment]
I think the event system in mios requires that you use their goofy gateway service, I haven't played around with events much but when I did, I couldn't get anything to work. If you find anything, let me know because I'd be super interested in incorporating that .. going to close this for now .. reopen when you find something :)
